version: "2"
services:
  api:
    build: .
    command: "pm2-docker process.json"
    ports:
      - "3777:3000"
    depends_on:
       - mongodb
    environment:
      NODE_ENV: development
      AUTH0_DOMAIN: "fun-media.eu.auth0.com"
      AUTH0_AUDIENCE: "http://localhost:3777/api"
      DB_NAME: "fun_media"
      DB_URL: mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    ports:
      - "27077:27017"
    image: mongo:latest
    volumes:
      - "mongodb:/data/db"
    command: --smallfiles --rest

volumes:
  mongodb:
    external:
      name: mongodb

networks:
  default:
    driver: bridge